# -*- coding: utf-8 -*-
"""Part 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EASDI9_8oSwS_M1EI5BMDKe7Ju-SDFew
"""

import pandas as pd
import numpy as np


# =========================================================
# 1. LOAD AND PREP DATA
# =========================================================

def load_data(filepath: str, sheet_name: str = "Bakery sales") -> pd.DataFrame:
    df = pd.read_excel(filepath, sheet_name=sheet_name)

    # Standardize column names
    df.columns = [c.strip().lower() for c in df.columns]

    required_cols = ["date", "time", "item", "quantity", "unit_price"]
    missing = [c for c in required_cols if c not in df.columns]
    if missing:
        raise ValueError(f"Missing required columns: {missing}")

    # Clean item names
    df = df[df["item"].notna()].copy()
    df["item"] = df["item"].astype(str).str.strip().str.upper()

    # Remove weird / non-product / grouped entries
    df = df[df["item"] != ""]
    df = df[df["item"] != "."]
    df = df[~df["item"].str.contains("ARTICLE", na=False)]
    df = df[~df["item"].str.contains("DIVERS", na=False)]
    df = df[~df["item"].str.contains("BOISSON", na=False)]
    df = df[~df["item"].str.contains("CAFE", na=False)]
    df = df[~df["item"].str.contains("THE", na=False)]
    df = df[~df["item"].str.contains("PLAT", na=False)]
    df = df[~df["item"].str.contains("FORMULE", na=False)]
    df = df[~df["item"].str.contains("TRAITEUR", na=False)]

    # Keep only valid rows
    df = df[(df["quantity"] > 0) & (df["unit_price"] >= 0)]

    # Build datetime
    df["datetime"] = pd.to_datetime(
        df["date"].astype(str) + " " + df["time"].astype(str),
        errors="coerce"
    )

    if df["datetime"].isna().any():
        bad_rows = df[df["datetime"].isna()][["date", "time"]]
        raise ValueError(f"Some date/time values could not be parsed:\n{bad_rows.head()}")

    df["hour"] = df["datetime"].dt.hour
    df["day"] = df["datetime"].dt.date
    df["revenue"] = df["quantity"] * df["unit_price"]

    return df


# =========================================================
# 2. HELPER FUNCTIONS
# =========================================================

def average_sale_time(df: pd.DataFrame, item_name: str) -> float:
    item_df = df[df["item"] == item_name].copy()

    if item_df.empty:
        raise ValueError(f"Item '{item_name}' not found.")

    weighted_avg_hour = (
        (item_df["hour"] * item_df["quantity"]).sum()
        / item_df["quantity"].sum()
    )
    return weighted_avg_hour


def build_hourly_baseline(df: pd.DataFrame) -> pd.DataFrame:
    return (
        df.groupby(["item", "hour"], as_index=False)
        .agg(
            total_quantity=("quantity", "sum"),
            avg_quantity=("quantity", "mean"),
            avg_price=("unit_price", "mean"),
            total_revenue=("revenue", "sum")
        )
    )


def build_daily_item_sales(df: pd.DataFrame) -> pd.DataFrame:
    return (
        df.groupby(["day", "item", "hour"], as_index=False)
        .agg(
            quantity_sold=("quantity", "sum"),
            avg_price=("unit_price", "mean")
        )
    )


# =========================================================
# 3. MARKOV INPUTS WITH NONZERO WASTE PROXY
# =========================================================

def estimate_markov_inputs_with_proxy(
    df: pd.DataFrame,
    item_name: str,
    discount_start_hour: int = 15,
    inventory_factor: float = 1.10,
    discount_sell_through_factor: float = 0.70
) -> dict:
    """
    Assumptions:
    - estimated inventory = avg_daily_sales * inventory_factor
    - not everything that reaches discount gets sold
    - discount_sell_through_factor controls how much of the observed
      after-discount sales potential actually converts into sell-through

    Interpretation:
    - p_sell_fresh: share of observed sales before discount hour
    - p_to_discount: share still unsold by the time discount begins
    - p_sell_discount: discounted-stage sell-through proxy
    - p_waste: leftover share after fresh + discount sales
    """

    item_df = df[df["item"] == item_name].copy()

    if item_df.empty:
        raise ValueError(f"Item '{item_name}' not found in dataset.")

    # Average daily sales
    daily_totals = item_df.groupby("day")["quantity"].sum()
    avg_daily_sales = daily_totals.mean()

    if pd.isna(avg_daily_sales) or avg_daily_sales == 0:
        raise ValueError(f"No valid daily sales found for item '{item_name}'.")

    # Assumed inventory (used as waste proxy base)
    estimated_inventory = avg_daily_sales * inventory_factor

    # Observed hourly sales timing
    hourly_total = item_df.groupby("hour")["quantity"].sum()
    total_sales = hourly_total.sum()

    if total_sales == 0:
        raise ValueError(f"No sales found for item '{item_name}'.")

    fresh_sales_observed = hourly_total[hourly_total.index < discount_start_hour].sum()
    after_discount_sales_observed = hourly_total[hourly_total.index >= discount_start_hour].sum()

    # Probability of selling before discount
    p_sell_fresh = fresh_sales_observed / total_sales

    # Probability of surviving until discount time
    p_to_discount = 1 - p_sell_fresh

    # Observed share of sales after discount hour
    observed_after_discount_share = after_discount_sales_observed / total_sales

    # Only a fraction of after-discount potential actually converts to sell-through
    p_sell_discount = min(
        observed_after_discount_share * discount_sell_through_factor,
        p_to_discount
    )

    # Leftover becomes waste
    p_waste = max(0.0, 1 - p_sell_fresh - p_sell_discount)

    return {
        "item": item_name,
        "discount_hour": discount_start_hour,
        "p_sell_fresh": p_sell_fresh,
        "p_to_discount": p_to_discount,
        "p_sell_discount": p_sell_discount,
        "p_waste": p_waste
    }


# =========================================================
# 4. MARKOV CHAIN FORMULATION
# =========================================================

def create_bakery_matrix(
    p_sell_fresh: float,
    p_to_discount: float,
    p_sell_discount: float,
    p_waste: float
) -> np.ndarray:
    """
    States:
    [Fresh, Discounted, Sold, Waste]
    """

    fresh_stay = max(0.0, 1 - p_sell_fresh - p_to_discount)
    discount_stay = max(0.0, 1 - p_sell_discount - p_waste)

    P = np.array([
        [fresh_stay,      p_to_discount, p_sell_fresh,    0.0],
        [0.0,             discount_stay, p_sell_discount, p_waste],
        [0.0,             0.0,           1.0,             0.0],
        [0.0,             0.0,           0.0,             1.0]
    ])

    return P


# =========================================================
# 5. EVALUATE MULTIPLE DISCOUNT TIMES FOR ONE ITEM
# =========================================================

def evaluate_discount_hours_with_proxy(
    df: pd.DataFrame,
    item_name: str,
    discount_hours: list,
    inventory_factor: float = 1.10,
    discount_sell_through_factor: float = 0.70
) -> pd.DataFrame:
    results = []

    for hour in discount_hours:
        params = estimate_markov_inputs_with_proxy(
            df=df,
            item_name=item_name,
            discount_start_hour=hour,
            inventory_factor=inventory_factor,
            discount_sell_through_factor=discount_sell_through_factor
        )

        matrix = create_bakery_matrix(
            p_sell_fresh=params["p_sell_fresh"],
            p_to_discount=params["p_to_discount"],
            p_sell_discount=params["p_sell_discount"],
            p_waste=params["p_waste"]
        )

        results.append({
            "item": params["item"],
            "discount_hour": params["discount_hour"],
            "p_sell_fresh": params["p_sell_fresh"],
            "p_to_discount": params["p_to_discount"],
            "p_sell_discount": params["p_sell_discount"],
            "p_waste": params["p_waste"],
            "transition_matrix": matrix
        })

    return pd.DataFrame(results)


# =========================================================
# 6. EVALUATE ALL ITEMS
# =========================================================

def evaluate_all_items_with_proxy(
    df: pd.DataFrame,
    discount_hours: list,
    inventory_factor: float = 1.10,
    discount_sell_through_factor: float = 0.70
) -> pd.DataFrame:
    all_results = []

    items = sorted(df["item"].dropna().unique())

    for item in items:
        try:
            item_results = evaluate_discount_hours_with_proxy(
                df=df,
                item_name=item,
                discount_hours=discount_hours,
                inventory_factor=inventory_factor,
                discount_sell_through_factor=discount_sell_through_factor
            )
            all_results.append(item_results)
        except Exception as e:
            print(f"Skipping {item}: {e}")

    if not all_results:
        return pd.DataFrame()

    return pd.concat(all_results, ignore_index=True)


# =========================================================
# 7. MAIN RUN
# =========================================================

if __name__ == "__main__":
    filepath = "Datasets.xlsx"
    discount_hours = [12, 13, 14, 15, 16, 17, 18]

    # Assumptions
    inventory_factor = 1.10
    discount_sell_through_factor = 0.70

    # Load data
    df = load_data(filepath)

    # Optional supporting tables
    hourly_baseline = build_hourly_baseline(df)
    daily_sales = build_daily_item_sales(df)

    # Run Markov stage
    results_df = evaluate_all_items_with_proxy(
        df=df,
        discount_hours=discount_hours,
        inventory_factor=inventory_factor,
        discount_sell_through_factor=discount_sell_through_factor
    )

    # Save full results
    results_df.to_csv("markov_results_with_waste_proxy.csv", index=False)
    print("Saved full results to markov_results_with_waste_proxy.csv")

    # Summary
    print("\n" + "=" * 60)
    print("SUMMARY")
    print("=" * 60)
    print(f"Total items analyzed: {results_df['item'].nunique()}")
    print(f"Total rows: {len(results_df)}")

    # Show only key items
    items_to_show = ["TRADITIONAL BAGUETTE", "CROISSANT"]

    print("\n" + "=" * 60)
    print("SAMPLE ITEM RESULTS")
    print("=" * 60)

    for item in items_to_show:
        item_df = results_df[results_df["item"] == item]

        if item_df.empty:
            print(f"\nItem: {item} not found in results.")
            continue

        print(f"\nItem: {item}")
        print("-" * 60)
        print(item_df[[
            "discount_hour",
            "p_sell_fresh",
            "p_to_discount",
            "p_sell_discount",
            "p_waste"
        ]].round(4).to_string(index=False))

    # Show one transition matrix
    print("\n" + "=" * 60)
    print("TRANSITION MATRIX (TRADITIONAL BAGUETTE)")
    print("=" * 60)

    selected_item = "TRADITIONAL BAGUETTE"
    selected_hour = 12

    selected_row = results_df[
        (results_df["item"] == selected_item) &
        (results_df["discount_hour"] == selected_hour)
    ]

    if selected_row.empty:
        print(f"No data found for {selected_item} at {selected_hour}:00")
    else:
        row = selected_row.iloc[0]
        print(f"\nItem: {row['item']} | Discount Hour: {row['discount_hour']}:00")

        matrix_df = pd.DataFrame(
            row["transition_matrix"],
            index=["Fresh", "Discounted", "Sold", "Waste"],
            columns=["Fresh", "Discounted", "Sold", "Waste"]
        )
        print(matrix_df.round(4))

    # Show average sale time for one key item
    avg_hour = average_sale_time(df, "TRADITIONAL BAGUETTE")
    avg_h = int(avg_hour)
    avg_m = int((avg_hour - avg_h) * 60)

    print("\n" + "=" * 60)
    print("AVERAGE SALE TIME")
    print("=" * 60)
    print(f"TRADITIONAL BAGUETTE average sale time: {avg_h:02d}:{avg_m:02d}")